//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringMath.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngineeringMath.Resources.LibraryResources", typeof(LibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Functions.
        /// </summary>
        public static string AllFunctions {
            get {
                return ResourceManager.GetString("AllFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Units.
        /// </summary>
        public static string AllUnits {
            get {
                return ResourceManager.GetString("AllUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to area of a circle.
        /// </summary>
        public static string AreaOfCircle {
            get {
                return ResourceManager.GetString("AreaOfCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmospheres.
        /// </summary>
        public static string Atmospheres {
            get {
                return ResourceManager.GetString("Atmospheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bernoullis Equation.
        /// </summary>
        public static string BernoullisEquation {
            get {
                return ResourceManager.GetString("BernoullisEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Thermal Units.
        /// </summary>
        public static string BTU {
            get {
                return ResourceManager.GetString("BTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        public static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Output(s).
        /// </summary>
        public static string ChangeOutputs {
            get {
                return ResourceManager.GetString("ChangeOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DaysAbbrev {
            get {
                return ResourceManager.GetString("DaysAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Coefficient.
        /// </summary>
        public static string DischargeCoefficient {
            get {
                return ResourceManager.GetString("DischargeCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not replace the parameter with a function.
        /// </summary>
        public static string DontReplaceParameter {
            get {
                return ResourceManager.GetString("DontReplaceParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthalpy.
        /// </summary>
        public static string Enthalpy {
            get {
                return ResourceManager.GetString("Enthalpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthalpy and Pressure.
        /// </summary>
        public static string EnthalpyAndPressure {
            get {
                return ResourceManager.GetString("EnthalpyAndPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy.
        /// </summary>
        public static string Entropy {
            get {
                return ResourceManager.GetString("Entropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy and Pressure.
        /// </summary>
        public static string EntropyAndPressure {
            get {
                return ResourceManager.GetString("EntropyAndPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find thermodynamic data with.
        /// </summary>
        public static string FindThermoDataWith {
            get {
                return ResourceManager.GetString("FindThermoDataWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid Dynamics.
        /// </summary>
        public static string FluidDynamics {
            get {
                return ResourceManager.GetString("FluidDynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons.
        /// </summary>
        public static string Gallons {
            get {
                return ResourceManager.GetString("Gallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grams.
        /// </summary>
        public static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horsepower.
        /// </summary>
        public static string Horsepower {
            get {
                return ResourceManager.GetString("Horsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string HoursAbbrev {
            get {
                return ResourceManager.GetString("HoursAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial System.
        /// </summary>
        public static string ImperialSystem {
            get {
                return ResourceManager.GetString("ImperialSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        public static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet {0}.
        /// </summary>
        public static string InletBlank {
            get {
                return ResourceManager.GetString("InletBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Pipe Area.
        /// </summary>
        public static string InletPipeArea {
            get {
                return ResourceManager.GetString("InletPipeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        public static string Inputs {
            get {
                return ResourceManager.GetString("Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Energy.
        /// </summary>
        public static string InternalEnergy {
            get {
                return ResourceManager.GetString("InternalEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isobaric Heat Capacity.
        /// </summary>
        public static string IsobaricHeatCapacity {
            get {
                return ResourceManager.GetString("IsobaricHeatCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isochoric Heat Capacity.
        /// </summary>
        public static string IsochoricHeatCapacity {
            get {
                return ResourceManager.GetString("IsochoricHeatCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isothermal Compressibility.
        /// </summary>
        public static string IsothermalCompressibility {
            get {
                return ResourceManager.GetString("IsothermalCompressibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joules.
        /// </summary>
        public static string Joules {
            get {
                return ResourceManager.GetString("Joules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        public static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilocalories.
        /// </summary>
        public static string Kilocalories {
            get {
                return ResourceManager.GetString("Kilocalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        public static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilojoules.
        /// </summary>
        public static string Kilojoules {
            get {
                return ResourceManager.GetString("Kilojoules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilopascals.
        /// </summary>
        public static string Kilopascals {
            get {
                return ResourceManager.GetString("Kilopascals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilowatt.
        /// </summary>
        public static string Kilowatt {
            get {
                return ResourceManager.GetString("Kilowatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid.
        /// </summary>
        public static string Liquid {
            get {
                return ResourceManager.GetString("Liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Fraction.
        /// </summary>
        public static string LiquidFraction {
            get {
                return ResourceManager.GetString("LiquidFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Vapor.
        /// </summary>
        public static string LiquidVapor {
            get {
                return ResourceManager.GetString("LiquidVapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        public static string Liters {
            get {
                return ResourceManager.GetString("Liters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric System.
        /// </summary>
        public static string MetricSystem {
            get {
                return ResourceManager.GetString("MetricSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Tons.
        /// </summary>
        public static string MetricTons {
            get {
                return ResourceManager.GetString("MetricTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micrograms.
        /// </summary>
        public static string Micrograms {
            get {
                return ResourceManager.GetString("Micrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milligrams.
        /// </summary>
        public static string Milligrams {
            get {
                return ResourceManager.GetString("Milligrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliters.
        /// </summary>
        public static string Milliliters {
            get {
                return ResourceManager.GetString("Milliliters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters.
        /// </summary>
        public static string Millimeters {
            get {
                return ResourceManager.GetString("Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        public static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string MillisecondsAbbrev {
            get {
                return ResourceManager.GetString("MillisecondsAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MinutesAbbrev {
            get {
                return ResourceManager.GetString("MinutesAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orifice Area.
        /// </summary>
        public static string OrificeArea {
            get {
                return ResourceManager.GetString("OrificeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orifice Plate.
        /// </summary>
        public static string OrificePlate {
            get {
                return ResourceManager.GetString("OrificePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        public static string Ounces {
            get {
                return ResourceManager.GetString("Ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet {0}.
        /// </summary>
        public static string OutletBlank {
            get {
                return ResourceManager.GetString("OutletBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string Outputs {
            get {
                return ResourceManager.GetString("Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pascals.
        /// </summary>
        public static string Pascals {
            get {
                return ResourceManager.GetString("Pascals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number between {0:G4} and {1:G4}..
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds-Force per Square Inch.
        /// </summary>
        public static string PoundsForcePerSqIn {
            get {
                return ResourceManager.GetString("PoundsForcePerSqIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds Mass.
        /// </summary>
        public static string PoundsMass {
            get {
                return ResourceManager.GetString("PoundsMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Drop.
        /// </summary>
        public static string PressureDrop {
            get {
                return ResourceManager.GetString("PressureDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankine.
        /// </summary>
        public static string Rankine {
            get {
                return ResourceManager.GetString("Rankine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation Pressure.
        /// </summary>
        public static string SatPressure {
            get {
                return ResourceManager.GetString("SatPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation Temperature.
        /// </summary>
        public static string SatTemperature {
            get {
                return ResourceManager.GetString("SatTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string SecondsAbbrev {
            get {
                return ResourceManager.GetString("SecondsAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string SIAbbrev {
            get {
                return ResourceManager.GetString("SIAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International System of Units.
        /// </summary>
        public static string SIFullName {
            get {
                return ResourceManager.GetString("SIFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        public static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Fraction.
        /// </summary>
        public static string SolidFraction {
            get {
                return ResourceManager.GetString("SolidFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Liquid.
        /// </summary>
        public static string SolidLiquid {
            get {
                return ResourceManager.GetString("SolidLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Liquid Vapor.
        /// </summary>
        public static string SolidLiquidVapor {
            get {
                return ResourceManager.GetString("SolidLiquidVapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Vapor.
        /// </summary>
        public static string SolidVapor {
            get {
                return ResourceManager.GetString("SolidVapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        public static string Solve {
            get {
                return ResourceManager.GetString("Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve for {0}.
        /// </summary>
        public static string SolveFor {
            get {
                return ResourceManager.GetString("SolveFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve using {0}.
        /// </summary>
        public static string SolveUsingFunction {
            get {
                return ResourceManager.GetString("SolveUsingFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Volume.
        /// </summary>
        public static string SpecificVolume {
            get {
                return ResourceManager.GetString("SpecificVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed of Sound.
        /// </summary>
        public static string SpeedOfSound {
            get {
                return ResourceManager.GetString("SpeedOfSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Table.
        /// </summary>
        public static string SteamTable {
            get {
                return ResourceManager.GetString("SteamTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supercritical Fluid.
        /// </summary>
        public static string SupercriticalFluid {
            get {
                return ResourceManager.GetString("SupercriticalFluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature and Pressure.
        /// </summary>
        public static string TemperatureAndPressure {
            get {
                return ResourceManager.GetString("TemperatureAndPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermodynamics.
        /// </summary>
        public static string Thermodynamics {
            get {
                return ResourceManager.GetString("Thermodynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermodynamic Region.
        /// </summary>
        public static string ThermoRegion {
            get {
                return ResourceManager.GetString("ThermoRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Therms.
        /// </summary>
        public static string Therms {
            get {
                return ResourceManager.GetString("Therms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torr.
        /// </summary>
        public static string Torr {
            get {
                return ResourceManager.GetString("Torr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Cubed.
        /// </summary>
        public static string UnitCubed {
            get {
                return ResourceManager.GetString("UnitCubed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Squared.
        /// </summary>
        public static string UnitSquared {
            get {
                return ResourceManager.GetString("UnitSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to the {1}th power.
        /// </summary>
        public static string UnitToTheNthPower {
            get {
                return ResourceManager.GetString("UnitToTheNthPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USCS.
        /// </summary>
        public static string USCSAbbrev {
            get {
                return ResourceManager.GetString("USCSAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States customary system.
        /// </summary>
        public static string USCSFullName {
            get {
                return ResourceManager.GetString("USCSFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Direct Input.
        /// </summary>
        public static string UseDirectInput {
            get {
                return ResourceManager.GetString("UseDirectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Direct Output.
        /// </summary>
        public static string UseDirectOutput {
            get {
                return ResourceManager.GetString("UseDirectOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Tons.
        /// </summary>
        public static string USTons {
            get {
                return ResourceManager.GetString("USTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapor.
        /// </summary>
        public static string Vapor {
            get {
                return ResourceManager.GetString("Vapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapor Fraction.
        /// </summary>
        public static string VaporFraction {
            get {
                return ResourceManager.GetString("VaporFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Expansivity.
        /// </summary>
        public static string VolumeExpansivity {
            get {
                return ResourceManager.GetString("VolumeExpansivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumetric Flow Rate.
        /// </summary>
        public static string VolumetricFlowRate {
            get {
                return ResourceManager.GetString("VolumetricFlowRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watt.
        /// </summary>
        public static string Watt {
            get {
                return ResourceManager.GetString("Watt", resourceCulture);
            }
        }
    }
}
