//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringMath.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngineeringMath.Resources.LibraryResources", typeof(LibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmospheres.
        /// </summary>
        public static string Atmospheres {
            get {
                return ResourceManager.GetString("Atmospheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Thermal Units.
        /// </summary>
        public static string BTU {
            get {
                return ResourceManager.GetString("BTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        public static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthalpy.
        /// </summary>
        public static string Enthalpy {
            get {
                return ResourceManager.GetString("Enthalpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy.
        /// </summary>
        public static string Entropy {
            get {
                return ResourceManager.GetString("Entropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grams.
        /// </summary>
        public static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horsepower.
        /// </summary>
        public static string Horsepower {
            get {
                return ResourceManager.GetString("Horsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        public static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joules.
        /// </summary>
        public static string Joules {
            get {
                return ResourceManager.GetString("Joules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        public static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilocalories.
        /// </summary>
        public static string Kilocalories {
            get {
                return ResourceManager.GetString("Kilocalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        public static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilojoules.
        /// </summary>
        public static string Kilojoules {
            get {
                return ResourceManager.GetString("Kilojoules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilopascals.
        /// </summary>
        public static string Kilopascals {
            get {
                return ResourceManager.GetString("Kilopascals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilowatt.
        /// </summary>
        public static string Kilowatt {
            get {
                return ResourceManager.GetString("Kilowatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Tons.
        /// </summary>
        public static string MetricTons {
            get {
                return ResourceManager.GetString("MetricTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micrograms.
        /// </summary>
        public static string Micrograms {
            get {
                return ResourceManager.GetString("Micrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milligrams.
        /// </summary>
        public static string Milligrams {
            get {
                return ResourceManager.GetString("Milligrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters.
        /// </summary>
        public static string Millimeters {
            get {
                return ResourceManager.GetString("Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        public static string Ounces {
            get {
                return ResourceManager.GetString("Ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pascals.
        /// </summary>
        public static string Pascals {
            get {
                return ResourceManager.GetString("Pascals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds-Force per Square Inch.
        /// </summary>
        public static string PoundsForcePerSqIn {
            get {
                return ResourceManager.GetString("PoundsForcePerSqIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds Mass.
        /// </summary>
        public static string PoundsMass {
            get {
                return ResourceManager.GetString("PoundsMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankine.
        /// </summary>
        public static string Rankine {
            get {
                return ResourceManager.GetString("Rankine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Therms.
        /// </summary>
        public static string Therms {
            get {
                return ResourceManager.GetString("Therms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torr.
        /// </summary>
        public static string Torr {
            get {
                return ResourceManager.GetString("Torr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Cubed.
        /// </summary>
        public static string UnitCubed {
            get {
                return ResourceManager.GetString("UnitCubed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Inversed.
        /// </summary>
        public static string UnitInversed {
            get {
                return ResourceManager.GetString("UnitInversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Squared.
        /// </summary>
        public static string UnitSquared {
            get {
                return ResourceManager.GetString("UnitSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Tons.
        /// </summary>
        public static string USTons {
            get {
                return ResourceManager.GetString("USTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watt.
        /// </summary>
        public static string Watt {
            get {
                return ResourceManager.GetString("Watt", resourceCulture);
            }
        }
    }
}
