//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringMath.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngineeringMath.Resources.LibraryResources", typeof(LibraryResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ChE.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bernoulli&apos;s Equation.
        /// </summary>
        public static string BernoullisEquation {
            get {
                return ResourceManager.GetString("BernoullisEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler Efficiency.
        /// </summary>
        public static string BoilerEfficiency {
            get {
                return ResourceManager.GetString("BoilerEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler Heat Transfer Rate.
        /// </summary>
        public static string BoilerHeatTransRate {
            get {
                return ResourceManager.GetString("BoilerHeatTransRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler Work.
        /// </summary>
        public static string BoilerWork {
            get {
                return ResourceManager.GetString("BoilerWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular Pipe.
        /// </summary>
        public static string CircularPipe {
            get {
                return ResourceManager.GetString("CircularPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condenser Heat Transfer Rate.
        /// </summary>
        public static string CondenserHeatTransRate {
            get {
                return ResourceManager.GetString("CondenserHeatTransRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condenser Pressure.
        /// </summary>
        public static string CondenserPressure {
            get {
                return ResourceManager.GetString("CondenserPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condenser Steam Quality Fraction.
        /// </summary>
        public static string CondenserSQ {
            get {
                return ResourceManager.GetString("CondenserSQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condenser Work.
        /// </summary>
        public static string CondenserWork {
            get {
                return ResourceManager.GetString("CondenserWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction Coefficient.
        /// </summary>
        public static string CorrectionCo {
            get {
                return ResourceManager.GetString("CorrectionCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta P.
        /// </summary>
        public static string DeltaP {
            get {
                return ResourceManager.GetString("DeltaP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Input.
        /// </summary>
        public static string DirectInput {
            get {
                return ResourceManager.GetString("DirectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Coefficient.
        /// </summary>
        public static string DischargeCoefficient {
            get {
                return ResourceManager.GetString("DischargeCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthalpy.
        /// </summary>
        public static string Enthalpy {
            get {
                return ResourceManager.GetString("Enthalpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy.
        /// </summary>
        public static string Entropy {
            get {
                return ResourceManager.GetString("Entropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR!.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid Density.
        /// </summary>
        public static string FluidDensity {
            get {
                return ResourceManager.GetString("FluidDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluids.
        /// </summary>
        public static string Fluids {
            get {
                return ResourceManager.GetString("Fluids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid Velocity.
        /// </summary>
        public static string FluidVelocity {
            get {
                return ResourceManager.GetString("FluidVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given.
        /// </summary>
        public static string Given {
            get {
                return ResourceManager.GetString("Given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet.
        /// </summary>
        public static string Inlet {
            get {
                return ResourceManager.GetString("Inlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Height.
        /// </summary>
        public static string InletHeight {
            get {
                return ResourceManager.GetString("InletHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet - Outlet.
        /// </summary>
        public static string InletMinusOutlet {
            get {
                return ResourceManager.GetString("InletMinusOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Pressure.
        /// </summary>
        public static string InletP {
            get {
                return ResourceManager.GetString("InletP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Pipe Area.
        /// </summary>
        public static string InletPipeArea {
            get {
                return ResourceManager.GetString("InletPipeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet\xB2 - Outlet\xB2.
        /// </summary>
        public static string InletSquaredMinusOutletSquared {
            get {
                return ResourceManager.GetString("InletSquaredMinusOutletSquared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Velocity.
        /// </summary>
        public static string InletVelo {
            get {
                return ResourceManager.GetString("InletVelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid.
        /// </summary>
        public static string Liquid {
            get {
                return ResourceManager.GetString("Liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manometer Height Differential.
        /// </summary>
        public static string ManoDeltaH {
            get {
                return ResourceManager.GetString("ManoDeltaH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manometer Density.
        /// </summary>
        public static string ManoDensity {
            get {
                return ResourceManager.GetString("ManoDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Flow Rate.
        /// </summary>
        public static string MassFlowRate {
            get {
                return ResourceManager.GetString("MassFlowRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Work.
        /// </summary>
        public static string NetWork {
            get {
                return ResourceManager.GetString("NetWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Saturated Species.
        /// </summary>
        public static string NonSaturatedSpecies {
            get {
                return ResourceManager.GetString("NonSaturatedSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number!.
        /// </summary>
        public static string NotANumber {
            get {
                return ResourceManager.GetString("NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orifice Area.
        /// </summary>
        public static string OrificeArea {
            get {
                return ResourceManager.GetString("OrificeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orifice Plate.
        /// </summary>
        public static string OrificePlate {
            get {
                return ResourceManager.GetString("OrificePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet.
        /// </summary>
        public static string Outlet {
            get {
                return ResourceManager.GetString("Outlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Height.
        /// </summary>
        public static string OutletHeight {
            get {
                return ResourceManager.GetString("OutletHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Pressure.
        /// </summary>
        public static string OutletP {
            get {
                return ResourceManager.GetString("OutletP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Velocity.
        /// </summary>
        public static string OutletVelo {
            get {
                return ResourceManager.GetString("OutletVelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output could not be calculated!.
        /// </summary>
        public static string OutputCouldBeCalculated {
            get {
                return ResourceManager.GetString("OutputCouldBeCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number between {0} and {1}.
        /// </summary>
        public static string ParameterValidRange {
            get {
                return ResourceManager.GetString("ParameterValidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop in Pressure (pIn - pOut).
        /// </summary>
        public static string PDAcrossOP {
            get {
                return ResourceManager.GetString("PDAcrossOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        public static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PitotTube.
        /// </summary>
        public static string PitotTube {
            get {
                return ResourceManager.GetString("PitotTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Requirement.
        /// </summary>
        public static string PowerRequirement {
            get {
                return ResourceManager.GetString("PowerRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump Efficiency.
        /// </summary>
        public static string PumpEfficiency {
            get {
                return ResourceManager.GetString("PumpEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump Work.
        /// </summary>
        public static string PumpWork {
            get {
                return ResourceManager.GetString("PumpWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankine Cycle.
        /// </summary>
        public static string RankineCycle {
            get {
                return ResourceManager.GetString("RankineCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regeneration Stages.
        /// </summary>
        public static string RegenerationStages {
            get {
                return ResourceManager.GetString("RegenerationStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerative Cycle.
        /// </summary>
        public static string RegenerativeCycle {
            get {
                return ResourceManager.GetString("RegenerativeCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated Temperature.
        /// </summary>
        public static string SatTemperature {
            get {
                return ResourceManager.GetString("SatTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated Species.
        /// </summary>
        public static string SaturatedSpecies {
            get {
                return ResourceManager.GetString("SaturatedSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve For.
        /// </summary>
        public static string SolveFor {
            get {
                return ResourceManager.GetString("SolveFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Volume.
        /// </summary>
        public static string SpecificVolume {
            get {
                return ResourceManager.GetString("SpecificVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Pressure.
        /// </summary>
        public static string SteamPressure {
            get {
                return ResourceManager.GetString("SteamPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Rate.
        /// </summary>
        public static string SteamRate {
            get {
                return ResourceManager.GetString("SteamRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Table.
        /// </summary>
        public static string SteamTable {
            get {
                return ResourceManager.GetString("SteamTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Temperature.
        /// </summary>
        public static string SteamTemp {
            get {
                return ResourceManager.GetString("SteamTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Substitute Function.
        /// </summary>
        public static string SubFunction {
            get {
                return ResourceManager.GetString("SubFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Efficiency.
        /// </summary>
        public static string ThermalEfficiency {
            get {
                return ResourceManager.GetString("ThermalEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermo.
        /// </summary>
        public static string Thermo {
            get {
                return ResourceManager.GetString("Thermo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermodynamic Cycle.
        /// </summary>
        public static string ThermodynamicCycle {
            get {
                return ResourceManager.GetString("ThermodynamicCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine Efficiency.
        /// </summary>
        public static string TurbineEfficiency {
            get {
                return ResourceManager.GetString("TurbineEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine Work.
        /// </summary>
        public static string TurbineWork {
            get {
                return ResourceManager.GetString("TurbineWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception of type {0} caught: {1}.
        /// </summary>
        public static string UnexpectedException {
            get {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Converter.
        /// </summary>
        public static string UnitConverter {
            get {
                return ResourceManager.GetString("UnitConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitless.
        /// </summary>
        public static string Unitless {
            get {
                return ResourceManager.GetString("Unitless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than or equal to {0}!.
        /// </summary>
        public static string ValueAboveUpperLimit {
            get {
                return ResourceManager.GetString("ValueAboveUpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to {0}!.
        /// </summary>
        public static string ValueBelowLowerLimit {
            get {
                return ResourceManager.GetString("ValueBelowLowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapor.
        /// </summary>
        public static string Vapor {
            get {
                return ResourceManager.GetString("Vapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumetric Flow Rate.
        /// </summary>
        public static string VolumetricFlowRate {
            get {
                return ResourceManager.GetString("VolumetricFlowRate", resourceCulture);
            }
        }
    }
}
